### ISSUE TITLE
Issues with login and LDAP

### ISSUE THREAD

**Issue by mitar** [socialappslab/appcivist-pb-client#1145] opened 2018-05-02 23:30 UTC
It seems there are some issues with login through LDAP.

* ~~Why is sometimes asking for an e-mail instead of username?~~
* When I enter username, and confirm login, there is briefly some e-mail shown, why?
* ~~And sometimes I get a regular non-LDAP login form?~~
* If I am on a proposal page, and I copy its URL into another tab, I get logged out in that tab and I get redirected to a non-LDAP login form, why?
* Why do I even have to login in each tab separately? If I am logged in into one tab, I should be logged in in whole browser like it is normal for regular apps. People are used to this.

(Edited: Removed duplicate entries, added the issue of having to log multiple times in separate tabs.)

**Comment by mitar** [comment] 2018-05-03 14:57
This is really bad. If I store a link to my contribution/proposal page (in e-mail or bookmark) and I visit it later on, I am prompted with login screen which is not an LDAP login screen. And I cannot login. Even if I was just logged in in another tab.

**Comment by jamesholston** [comment] 2018-05-03 17:25
Why is sometimes asking for an e-mail instead of username?  
-- I do not get this request for an email.  I only get request for ldap username.  Same with unifesp testers.  We cannot reproduce an email username request.

When I enter username, and confirm login, there is briefly some e-mail shown, why?
-- This is the case for me and unifesp testers too.  Don't know why.  Tech director Marcello thinks it is an AppCivist config issue.

And sometimes I get a regular non-LDAP login form?
-- This problem occurs occasionally with me too.  However, I have not yet documented the conditions that produce it.  It has occurred when I log out of the proposal page. I have not tried copying to another tab. Clearly, this situation is bad.  There is nothing to do from the non-ldap login screen but open a new tab and start over.

If I am on a proposal page, and I copy its URL into another tab, I get logged out in that tab and I get redirected to a non-LDAP login form, why?

**Comment by mitar** [comment] 2018-05-03 17:34
> I do not get this request for an email. I only get request for ldap username. Same with unifesp testers. We cannot reproduce an email username request.

I think this is when I open a link in new tab. I think I realized later on when is this happening. So that form after opening in new tab is the default one with e-mail.

**Comment by mitar** [comment] 2018-05-03 17:36
I edited the initial description a bit. I also added:

> Why do I even have to login in each tab separately? If I am logged in into one tab, I should be logged in in whole browser like it is normal for regular apps. People are used to this.

This is an issue which then makes other issues more common. If I would be logged in in whole browser, then copying the URL into another tab would not force me to log in again and redirect to default form.

**Comment by cdparra** [comment] 2018-05-07 22:01
Both redirecting to public URLs from non public ones and browser-wide sessions are now implemented. Closing this.

**Closed by cdparra** 2018-05-07 22:01 UTC

**Comment by mitar** [comment] 2018-05-08 00:50
No, this is not OK. Now if I send a link to a proposal and user is not logged in, they are just redirected to the public assembly page. What should happen is that they can login and then get to the proposal. Otherwise this is very confusing because they get misdirected away from where they want to go.

**Comment by cdparra** [comment] 2018-05-08 22:45
Can you copy here step by step, with examples, what you did? We tested this and it was working. What link exactly are you sharing?

**Comment by mitar** [comment] 2018-05-08 22:53
@cdparra James did that in the e-mail. See his e-mail for step to step reproduction.

**Comment by cdparra** [comment] 2018-05-09 01:45
Should be done now. There was one missing case.
