### ISSUE TITLE
Check "save resumo" action 

### ISSUE THREAD

**Issue by loorely** [socialappslab/appcivist-pb-client#1205] opened 2018-06-01 19:29 UTC
“salvar resumo” in production (around 1:25pm, see above).  It didn’t give confirmation and then caused my session to crash.

**Comment by cdparra** [comment] 2018-06-03 15:43
After many tests, I find no problem with the save summary. Closing this for now as there is no way of reproducing. 

Most likely, this was due to a connection leak on the verify users method, which caused the app to crash. That's already solved now.

**Closed by cdparra** 2018-06-03 15:43 UTC
